on:
  push: 
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Server SSH key
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/server_ssh
          chmod 600 ~/.ssh/server_key
      
      - name: Setting up SSH for GitHub
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
      
      - name: Deploy the server
        run: |
          ssh -i ~/.ssh/server_ssh ubuntu@20.115.88.88 << EOF
          cd ~/myproject/hng12-stage2-fastapi-with-pipeline
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart nginx
          sudo systemctl restart fast_api_service
          EOF
        