on:
  push: 
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setting up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy the server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@20.115.88.88 << EOF
          cd ~/myproject/hng12-stage2-fastapi-with-pipeline
          eval "$(ssh-agent -s)"
          ssh-add /home/ubuntu/.ssh/github_ssh
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart nginx
          sudo systemctl restart fast_api_service
          EOF
        