name: CI test file  

on:
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Setup Python Environment
              uses: actions/setup-python@v4
              with: 
                python-version: '3.12'
            

            - name: Installing Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run Tests
              run: pytest --maxfail=1